### ISSUE TITLE
Pass additional data with @submit

### ISSUE THREAD

**Issue by winterChroma** [trevoreyre/autocomplete#100]
Is there any way I can do this? Thanks.

**Comment by trevoreyre** [comment]
What data are you trying to pass? You can always put extra data in your results, and access those from the result object in the submit event.

**Comment by trevoreyre** [comment]
I haven't heard back, so I'm going to go ahead and close this one. Please feel free to reopen if you're still having issues.

**Comment by BFalls158** [comment]
Hi. Similar issue. I am generating multiple instances of the autocomplete component for a dynamic form and need to pass reference to the current value. 

<autocomplete
              :search="fetchVendors"
              :auto-select="true"
              :debounce-time="500"
              placeholder="Search"
              :get-result-value="getResults"
              @submit="onSubmit"
            />
            
This is inside of a v-for and I need the onSubmit function to also pass the context since v-model doesn't work. How exactly can I do this?

**Comment by trevoreyre** [comment]
@BFalls158 does #26 work for your case?

**Comment by BFalls158** [comment]
That will be perfect! Not sure how I missed it. Thanks
