### ISSUE TITLE
question

### ISSUE THREAD

**Issue by bwlegalmarkrobinson** [trevoreyre/autocomplete#18]
Hi,

In vue.js can I bind the initial value / default value so that when my page initially loads it has the data in the autocomplete i grab from a database?

Cheers
Mark

**Comment by trevoreyre** [comment]
Yeah, you should be able to use the `defaultValue` prop for that. [Here's an example](https://autocomplete.trevoreyre.com/#/vue-component?id=defaultvalue).

Let me know if that works for you.

**Comment by kereeen** [comment]
Hello,

Tried using <autocomplete :search="search" :default-value="getName" @submit="handleSubmit"></autocomplete>, but it doesn't show the value from the computed I made.

Hope you can help

**Comment by trevoreyre** [comment]
@kereeen I can't tell without seeing the rest of your code. Can you provide an example on Codepen or CodeSandbox or something?

**Comment by kereeen** [comment]
`<template>
</template>
export default {
  name: 'DynamicMain',
  data () {
        steps: []
    },
 computed: {
getName() {
      var name= this.$store.getters['employees/name'];

      return name
    }
}
  },`

**Comment by kereeen** [comment]
Hi. For some reason I just noticed that this `:default-value` is showing the value from the getter to the autocomplete field. Thanks!

**Comment by trevoreyre** [comment]
@kereeen Great! Glad to hear it's working.

**Comment by camilamercado** [comment]
@trevoreyre Thanks for this resource! Really helping me out. I ran into a similar issue when trying to pass a computed prop (or any other non-hardcoded variable) to the `default-variable` scope and am adding my workaround. 

Since the `autocomplete` component mounted before my computed value was set, it read my `default-value` property as `undefined` and defaulted to the `placeholder` content.

In order to get the computed value to populate `default-variable`, I had to add a watcher on my prop to re-render the `autocomplete` component once my var was set, following the force re-render pattern [described here](https://michaelnthiessen.com/force-re-render/).


```js
// pass string to default value
<template>
<autocomplete
    :key="componentKey" // must have key to trigger re-render
    :search="search"
    :default-value="term" // term is set in computed props
    @submit="onSubmit"
     >
...
</template>

import { mapState } from 'vuex'
import Autocomplete from '@trevoreyre/autocomplete-vue'

export default {
  name: 'SearchBar',
  components: {
    Autocomplete
  },
  data () {
    return {
      componentKey: 0 // set component key value
    }
  },
  computed: mapState([
    'term' // term is set by state manager
  ]),
methods: {
    forceRerender () {
    // force a re-render on component by updating key
      this.componentKey += 1
    }
},
watch: {
    term (newValue) {
      // when term is updated, tigger re-render method
      this.forceRerender()
    }
  }
}
